apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    helm.sh/hook-weight: "200"
    argocd.argoproj.io/sync-options: Prune=false
  name: cluster
spec:
  nodeSelector:
    node-role.kubernetes.io/foundational-services: "true"
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/foundational-services
      value: 'true'
      operator: Equal
  defaultRoute: true
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  proxy: {}
  replicas: 3
  requests:
    read:
      maxWaitInQueue: 0s
    write:
      maxWaitInQueue: 0s
  rolloutStrategy: RollingUpdate
  unsupportedConfigOverrides: null
