kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    config.openshift.io/inject-proxy: ingress-operator
    deployment.kubernetes.io/revision: '2'
  name: ingress-operator
  namespace: openshift-ingress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ingress-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ingress-operator
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
        node-role.kubernetes.io/foundational-services: "true"
      restartPolicy: Always
      serviceAccountName: ingress-operator
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            requests:
              cpu: 10m
          terminationMessagePath: /dev/termination-log
          name: ingress-operator
          command:
            - ingress-operator
            - start
            - '--namespace'
            - $(WATCH_NAMESPACE)
            - '--image'
            - $(IMAGE)
            - '--release-version'
            - $(RELEASE_VERSION)
          env:
            - name: RELEASE_VERSION
              value: 4.6.34
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: IMAGE
              value: >-
                quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:30e8835cc850cadbf1c1156ebfc5a4dd56625494db0ab8e25d008eb40d690087
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: trusted-ca
              readOnly: true
              mountPath: /etc/pki/ca-trust/extracted/pem
          terminationMessagePolicy: FallbackToLogsOnError
          image: >-
            quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:65dd8b76624959bd2a9871e22868e326ad34154dfede6beeccd0d6e5ba599467
        - resources:
            requests:
              cpu: 10m
              memory: 40Mi
          terminationMessagePath: /dev/termination-log
          name: kube-rbac-proxy
          ports:
            - name: metrics
              containerPort: 9393
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: metrics-tls
              readOnly: true
              mountPath: /etc/tls/private
          terminationMessagePolicy: File
          image: >-
            quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:25b62a00ea77d0f57906ee344a1416f3b0183aca8008e98a87cd5d06cfa4a690
          args:
            - '--logtostderr'
            - '--secure-listen-address=:9393'
            - >-
              --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
            - '--upstream=http://127.0.0.1:60000/'
            - '--tls-cert-file=/etc/tls/private/tls.crt'
            - '--tls-private-key-file=/etc/tls/private/tls.key'
      serviceAccount: ingress-operator
      volumes:
        - name: metrics-tls
          secret:
            secretName: metrics-tls
            defaultMode: 420
        - name: trusted-ca
          configMap:
            name: trusted-ca
            items:
              - key: ca-bundle.crt
                path: tls-ca-bundle.pem
            defaultMode: 420
      dnsPolicy: ClusterFirst
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
        - effect: NoSchedule
          key: node-role.kubernetes.io/foundational-services
          value: 'true'
          operator: Equal
      priorityClassName: system-cluster-critical
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

