apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-foundational-service-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: ibm-common-services
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: 2-services/instances/ibm-foundational
    repoURL: https://github.ibm.com/jesus-arteche/roks-split-1.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true