apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infraconfig
  annotations:
    argocd.argoproj.io/sync-wave: "102"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: apps
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
    jsonPointers:
    - /spec/defaultCertificate
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 3-infra/refarch-infraconfig
    repoURL: https://github.ibm.com/jesus-arteche/roks-split-1.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true